### ISSUE TITLE
能否说一下使用说明

### ISSUE THREAD

**Issue by Hawken94** [Novemser/calabashbrothersfight#12]
毕竟不太懂前端

**Comment by tsengkasing** [comment]
抱歉现在才看到您提的 issue。

## 说在前面：
此项目开发时前后端分离了，因此前端放在了 webpage 目录下，后端则放到了 server 目录下。
然后由于当时时间紧促，没有区分用户，所以同一时间内，只能有一个用户在操作，否则会混乱。
如有需要可通过添加 cookie 等方式区分用户，支持多用户同时使用。

## 使用说明：

### 前端：
1. 首先请在本机安装 Node.js 
2. 切换到代码的 webpage 目录下，执行

```shell
$ npm install
$ npm run build
```

便会在当前目录下，生成一个 dist 文件夹，此为打包后的前端文件。
请将此``dist``文件夹放在生产环境下的位置，并记录下绝对路径（以下要用到）。

### 后端：
1. 请在本机配置好 GO 的开发环境，请确保 GOPATH 配置在正确的位置
2. 修改``server/src/main.go`` 文件的 334行，337行，以及386行。
334行和337行，为后端托管静态资源的绝对路径，一个是 ``index.html``，另一个是 ``static`` 目录，都在前述的 ``dist`` 目录中。
386行则是监听的本地端口。

3. 修改完毕后，执行 ``$ go build`` 编译 go 代码，以二进制的方式执行即可。

目前也可前往 [http://go.everstar.xyz/](http://go.everstar.xyz/) 试用一下（单用户限制）

**Comment by Hawken94** [comment]
@tsengkasing 谢谢
